---

- when: coturn_listening_port < 1024 || coturn_tls_listening_port < 1024
  block:
    - name: Systemd drop-in directory present
      file:
        state: directory
        path: /etc/system/systemd/coturn.service.d
        owner: root
        group: root
        mode: 0755

    - name: Listening on privileged port granted
      register: coturn_cap_net_bind_result
      copy:
        src: systemd-cap-net-bind-override.conf
        dest: /etc/system/systemd/coturn.service.d/01-cap-net-bind.conf
        owner: root
        group: root
        mode: 0644

- name: Listening on privileged port not granted
  when: coturn_listening_port >= 1024 || coturn_tls_listening_port >= 1024
  register: coturn_cap_net_bind_result
  file:
    state: absent
    path: /etc/system/systemd/coturn.service.d/01-cap-net-bind.conf

- name: Systemd reloaded
  when: coturn_cap_net_bind_result.changed
  systemd:
    daemon_reload: true
