---

- when: coturn_listening_port < 1024 or coturn_tls_listening_port < 1024
  block:
    - name: Systemd drop-in directory present
      file:
        state: directory
        path: /etc/systemd/system/coturn.service.d
        owner: root
        group: root
        mode: 0755

    - name: Listening on privileged port granted
      register: coturn_cap_net_bind_result
      notify:
        - restart coturn
      copy:
        src: systemd-cap-net-bind-override.conf
        dest: /etc/systemd/system/coturn.service.d/01-cap-net-bind.conf
        owner: root
        group: root
        mode: 0644

    - name: Systemd daemon reloaded
      when: coturn_cap_net_bind_result is changed
      systemd:
        daemon_reload: true

- when: coturn_listening_port >= 1024 and coturn_tls_listening_port >= 1024
  block:
    - name: Listening on privileged port not granted
      register: coturn_cap_net_bind_result
      notify:
        - restart coturn
      file:
        state: absent
        path: /etc/systemd/system/coturn.service.d/01-cap-net-bind.conf

    - name: Systemd daemon reloaded
      when: coturn_cap_net_bind_result is changed
      systemd:
        daemon_reload: true
